version: '2'

services:

  db:
    image: mysql:5.6
    ports:
    - 3306:3306
    environment:
    - MYSQL_ROOT_PASSWORD=123456

  adminer:
    depends_on:
    - db
    image: adminer
    ports:
    - 8080:8080

  drupal:
    depends_on:
    - db
    image: gcr.io/midbarrn/midburn-profiles-drupal-latest:latest
